### ISSUE TITLE
Message Jobs doest work

### ISSUE THREAD

**Issue by JericoFX** [JericoFX/gcphone#5]
Check the message Jobs, it only send to the player not the rest of the team.

**Comment by Swompen** [comment]
It does not work, I tested on my local with a few friends.

So one issue is when you send a for example a police message the others dont get it. ONLY the person (If hes a police) gets the police message.

And then when you try to call a job you get the error below and it does not work.

![image](https://user-images.githubusercontent.com/16113909/104784761-46821b80-5789-11eb-9a6e-6ae570725dc9.png)

**Comment by JericoFX** [comment]
Check the las commit, I tested the call and work be sure everyone has the phone number correct loaded

**Comment by Swompen** [comment]
Aye, msg works now. Not calling tho.

**Comment by JericoFX** [comment]
Ok today i will test the calling, one question, that error is send every time when someone doest have the number, like didnt load properly and have the ####### in the number

**Comment by JericoFX** [comment]
and check again or update the phone but dont eliminate anything because in line 100 in server i have this 
https://prnt.sc/x579vl
